name: Build

on:
  push:
    branches:
      - master
    tags:
      - 'v*'
  pull_request: {}

jobs:
  build:
    permissions:
      contents: write

    runs-on: ubuntu-24.04-arm

    steps:
    - uses: actions/checkout@v5
    - uses: actions/cache@v4
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          target
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
    - run: cargo build --locked --release --target aarch64-unknown-linux-gnu
    - uses: actions/upload-artifact@v4
      with:
        name: arm64-binary
        path: target/aarch64-unknown-linux-gnu/release/solana-parser
    - env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      if: github.ref_type == 'tag'
      run: |
        gh release create ${{ github.ref_name }} \
          --title "${{ github.ref_name }}" \
          --target "${{ github.sha }}" \
          target/aarch64-unknown-linux-gnu/release/solana-parser
