name: Build

on:
  push:
    branches:
      - master
  pull_request: {}

jobs:
  build:
    runs-on: ubuntu-24.04-arm

    steps:
    - uses: actions/checkout@v5
    - uses: actions/cache@v4
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          target
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
    - run: cargo build --release --target aarch64-unknown-linux-gnu
    - uses: actions/upload-artifact@v4
      with:
        name: arm64-binary
        path: target/aarch64-unknown-linux-gnu/release/solana-parser
